# RENAME THIS FILE TO cfg.yaml
# IF U WANT TO USE IT IN APP

database:
  url: "urDbLogin:urPassword@/dbName" # connect string to ur databse
http_server:
  address: "localhost:3000" # the address where the app will run
  timeout: 4s # enter ur time using seconds or hours
  idle_timeout: 10s # enter ur time using seconds or hours
jwt_config:
  accessJwtSecret: "ur key" # enter ur secret
  refreshJwtSecret: "ur key" # enter ur secret
  accessJwtExpiredIn: 24h # enter ur time using ONLY hours or seconds
  refreshJwtExpiredIn: 720h # enter ur time using ONLY hours or seconds